### ISSUE TITLE
使用xe->bib->xe->xe编译链代替xelatex编译, vscode latex workshop 配置部分过时

### ISSUE THREAD

**Issue by geniusLcy** [xnth97/TJUThesisLatexTemplate#7]
## 编译
仅使用 xelatex tjumain.tex 编译不会生成目录、引用标号等，推荐README告诉大家直接xe->bib->xe->xe全家桶编译
```bash
xelatex tjumain.tex
bibtex tjumain.tex
xelatex tjumain.tex
xelatex tjumain.tex
```
## vscode
LaTeX Workshop部分的配置json已过时
## pr #6

**Comment by xnth97** [comment]
感谢PR！LGTM, minor comments

**Comment by xnth97** [comment]
PR merged. thanks for contribution
